// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOpBL1NuY_Q8OjOD_eJEGzI9oFfRw4tw',
    appId: '1:653124289726:web:1d565149c4c392bac70aef',
    messagingSenderId: '653124289726',
    projectId: 'rhemalize-church-audio-app',
    authDomain: 'rhemalize-church-audio-app.firebaseapp.com',
    storageBucket: 'rhemalize-church-audio-app.firebasestorage.app',
    measurementId: 'G-3MBEQN6D4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKz0ylFfvI2Ts5sJC_2-xjgZXco0gxSCI',
    appId: '1:653124289726:android:9192575c77ef8eaec70aef',
    messagingSenderId: '653124289726',
    projectId: 'rhemalize-church-audio-app',
    storageBucket: 'rhemalize-church-audio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkC3Stc1_g39_XMa5OPyY77ylEtkdFq-M',
    appId: '1:653124289726:ios:3f7fc7aaadc8f778c70aef',
    messagingSenderId: '653124289726',
    projectId: 'rhemalize-church-audio-app',
    storageBucket: 'rhemalize-church-audio-app.firebasestorage.app',
    androidClientId: '653124289726-dqcq281rj0u0p3ocpc9vnhtdsb7ugj0u.apps.googleusercontent.com',
    iosClientId: '653124289726-79u6ek1qo3rj0dnlm26n9u1hmu6h78be.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhemalizeChurchAudioAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkC3Stc1_g39_XMa5OPyY77ylEtkdFq-M',
    appId: '1:653124289726:ios:3f7fc7aaadc8f778c70aef',
    messagingSenderId: '653124289726',
    projectId: 'rhemalize-church-audio-app',
    storageBucket: 'rhemalize-church-audio-app.firebasestorage.app',
    androidClientId: '653124289726-dqcq281rj0u0p3ocpc9vnhtdsb7ugj0u.apps.googleusercontent.com',
    iosClientId: '653124289726-79u6ek1qo3rj0dnlm26n9u1hmu6h78be.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhemalizeChurchAudioAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzOpBL1NuY_Q8OjOD_eJEGzI9oFfRw4tw',
    appId: '1:653124289726:web:5f8164f619cbad6bc70aef',
    messagingSenderId: '653124289726',
    projectId: 'rhemalize-church-audio-app',
    authDomain: 'rhemalize-church-audio-app.firebaseapp.com',
    storageBucket: 'rhemalize-church-audio-app.firebasestorage.app',
    measurementId: 'G-EJ0KNXYW28',
  );
}
